import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

type JsonObject = Record<string, unknown>;
type ResolvedSemanticValue = string | number;

const root = process.cwd();
const tokenDirectory = path.join(root, "tokens");
const outputPath = path.join(
  root,
  "client",
  "tokens",
  "generated-design-tokens.ts",
);

function isObject(value: unknown): value is JsonObject {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

async function readJson(fileName: string): Promise<JsonObject> {
  const value: unknown = JSON.parse(
    await readFile(path.join(tokenDirectory, fileName), "utf8"),
  );

  if (!isObject(value)) {
    throw new Error(`${fileName} must contain a JSON object`);
  }

  return value;
}

function getTokenValue(token: unknown, tokenName: string): unknown {
  if (!isObject(token) || !("$value" in token)) {
    throw new Error(`Invalid DTCG token: ${tokenName}`);
  }

  return token.$value;
}

function resolvePrimitiveReference(
  primitives: JsonObject,
  reference: string,
): ResolvedSemanticValue {
  const [groupName, ...tokenNameParts] = reference.slice(1, -1).split(".");
  const tokenName = tokenNameParts.join(".");
  const group = primitives[groupName];

  if (!isObject(group)) {
    throw new Error(`Unknown primitive group: ${groupName}`);
  }

  return resolveValue(
    getTokenValue(group[tokenName], reference),
    primitives,
    reference,
  );
}

function resolveValue(
  value: unknown,
  primitives: JsonObject,
  tokenName: string,
): ResolvedSemanticValue {
  if (typeof value === "number") {
    return value;
  }

  if (typeof value === "string" && /^\{.+\}$/.test(value)) {
    return resolvePrimitiveReference(primitives, value);
  }

  if (isObject(value) && typeof value.hex === "string") {
    return value.hex;
  }

  throw new Error(`Unsupported DTCG value for: ${tokenName}`);
}

function resolveSemanticTokens(
  semantics: JsonObject,
  primitives: JsonObject,
): Record<string, ResolvedSemanticValue> {
  return Object.fromEntries(
    Object.entries(semantics).map(([tokenName, token]) => [
      tokenName,
      resolveValue(getTokenValue(token, tokenName), primitives, tokenName),
    ]),
  );
}

function resolveTypographyTokens(
  tokens: JsonObject,
): Record<string, JsonObject> {
  return Object.fromEntries(
    Object.entries(tokens).map(([tokenName, token]) => {
      const value = getTokenValue(token, tokenName);

      if (!isObject(value)) {
        throw new Error(`Invalid typography token: ${tokenName}`);
      }

      return [tokenName, value];
    }),
  );
}

function resolveDimensionTokens(tokens: JsonObject): Record<string, number> {
  return Object.fromEntries(
    Object.entries(tokens).map(([tokenName, token]) => {
      const value = getTokenValue(token, tokenName);

      if (typeof value !== "number") {
        throw new Error(`Invalid dimension token (expected number): ${tokenName}`);
      }

      return [tokenName, value];
    }),
  );
}

export async function generateDesignTokens(): Promise<void> {
  const [
    darkPrimitives,
    darkSemantics,
    lightPrimitives,
    lightSemantics,
    typography,
    dimensions,
  ] = await Promise.all([
    readJson("brandcyan.dark.primitive.tokens.json"),
    readJson("brandcyan.dark.semantic.tokens.json"),
    readJson("brandcyan.light.primitive.tokens.json"),
    readJson("brandcyan.light.semantic.tokens.json"),
    readJson("brandcyan.typography.styles.tokens.json"),
    readJson("brandcyan.dimensions.tokens.json"),
  ]);

  const output = `/* This file is generated by scripts/generate-design-tokens.ts. */
export const generatedThemes = ${JSON.stringify(
    {
      dark: resolveSemanticTokens(darkSemantics, darkPrimitives),
      light: resolveSemanticTokens(lightSemantics, lightPrimitives),
    },
    null,
    2,
  )} as const;

export const generatedTypographyTokens = ${JSON.stringify(
    resolveTypographyTokens(typography),
    null,
    2,
  )} as const;

export const generatedDimensionTokens = ${JSON.stringify(
    resolveDimensionTokens(dimensions),
    null,
    2,
  )} as const;
`;

  await writeFile(outputPath, output, "utf8");
}

const isDirectExecution =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isDirectExecution) {
  await generateDesignTokens();
}
